// ---------------------------------------------------------------------------------------------------------------------
// jsstrings_zh.js
//   This file is the copyrighted property of Tableau Software and is protected by registered patents and other
//   applicable U.S. and international laws and regulations.
//
//   Unlicensed use of the contents of this file is prohibited. Please refer to the NOTICES.txt file for further details.
// ---------------------------------------------------------------------------------------------------------------------
// WARNING: Computer generated file.  Do not hand modify.
// DEPENDS ON: ['codegen/resx-strings-js.template', 'workgroup/vqlweb/scriptsharp/src/Resources/Strings/Strings.en.resx', 'workgroup/vqlweb/scriptsharp/src/Resources/Strings/Strings.zh.resx']

(function(w) {
  var s = {
    AODialogBandTabTitle: "区间",
    AODialogCellScope: "单元格",
    AODialogComputationLabel: "计算",
    AODialogCustomLabelLabel: "自定义标签",
    AODialogCustomTooltipLabel: "自定义工具提示",
    AODialogDistributionTabTitle: "分布",
    AODialogFactorsLabel: "因子",
    AODialogFromValueLabel: "值 (自)",
    AODialogInstantAnalyticsBandLabel: "重新计算选定数据的区间",
    AODialogInstantAnalyticsLineLabel: "重新计算选定数据的线",
    AODialogLabelLabel: "标签",
    AODialogLineTabTitle: "线",
    AODialogNumberOfTilesLabel: "图块数",
    AODialogPaneScope: "区",
    AODialogPercentOfLabel: "百分比",
    AODialogPercentagesLabel: "百分比",
    AODialogPercentilesLabel: "百分位",
    AODialogQuantiles: "分位数",
    AODialogStandardDeviation: "标准差",
    AODialogTableScope: "表",
    AODialogTitleString: "编辑 {0}",
    AODialogToValueLabel: "值 (至)",
    AODialogTooltipLabel: "工具提示",
    AODialogValueLabel: "值",
    AccessbilityNotificationButtonDismissLabel: "关闭通知",
    AccessibilityClearSelectionInstructions: "按 ESC 清除任何标记选择。",
    AccessibilityDataVisualizationTitleAttr: "数据可视化",
    AccessibilityScrollSheetTabsLeft: "向左滚动工作表标签",
    AccessibilityScrollSheetTabsRight: "向右滚动工作表标签",
    AccessibilityViewDataDisabled: "未启用对“查看数据”窗口的访问。",
    AccessibilityViewDataInstructions: "若要打开“查看数据”窗口，请按 Control-Shift-Enter。",
    AddDataConnection: "添加数据源",
    AddDataConnectionAdd: "添加",
    AddDataConnectionCancel: "取消",
    AddDataExplanation: "选择发布的数据源以将其添加到您的工作簿。",
    AddDataLearnMore: "了解更多信息。",
    AddDataLearnToPublish: "了解如何向 Tableau Server 发布数据源。",
    AddDataNoPublishedDataSources: "没有可用的数据源。",
    AddDataNoSearchMatches: "没有数据源与您的搜索词匹配。",
    AddDataPublishRequirements: "若要发布新数据源，您必须是 {0} 的发布者。",
    AddDataSearchBrowseSuggestion: "滚动以浏览可用数据源的列表。",
    AddDataSearchDifferentTermsSuggestion: "使用其他词重试。",
    AddDataSearchSpellingSuggestion: "检查您的拼写。",
    AddDataSearchSuggestions: "搜索建议：",
    AddFloatingTextZoneInStoriesLabel: "双击以添加文本",
    AddSubscribers: "添加",
    AddSubscribersHeader: "添加订阅者",
    AddToLabel: "添加到:",
    AggregateCalcWarning: "此字段包含聚合计算，该计算仅包含可视化项的详细级别中的有意义数据。",
    AliasDialogHasAliasColumn: "有别名",
    AliasDialogMemberColumn: "成员",
    AliasDialogValueColumn: "值(别名)",
    April: "四月",
    AprilShort: "四月",
    AreYouSureCancel: "取消",
    AreYouSureDelete: "删除",
    AreYouSureText: "是否确定?",
    August: "八月",
    AugustShort: "八月",
    AuthCardCollapsedTitle: "{0} &middot; {1}",
    AuthCardTitleColumns: "列",
    AuthCardTitleFilters: "筛选器",
    AuthCardTitleMarks: "标记",
    AuthCardTitleMeasureValues: "度量值",
    AuthCardTitleMetricsDataFilters: "数据筛选器",
    AuthCardTitlePages: "页面",
    AuthCardTitleRows: "行",
    AuthColorEditingDisabled: "合并图例以在此处编辑颜色或编辑每个单独图例的颜色。",
    AuthColorPaletteAutomatic: "自动",
    AuthColorPaletteLegacy: "已停用",
    AuthColorPaletteMoreColors: "更多颜色...",
    AuthColorPaletteNone: "无",
    AuthColorTransparencyLabel: "不透明度",
    AuthConnectToDataSource: "连接到 {0} 上的数据源",
    AuthCustomHexColorLabel: "自定义颜色",
    AuthDashboardPaneBlankZone: "空白",
    AuthDashboardPaneButtonZone: "按钮",
    AuthDashboardPaneCarouselZone: "轮播",
    AuthDashboardPaneExtensionZone: "扩展",
    AuthDashboardPaneFloatingButton: "浮动",
    AuthDashboardPaneHorizontalZone: "水平",
    AuthDashboardPaneImageZone: "图像",
    AuthDashboardPaneNewObjects: "新对象:",
    AuthDashboardPaneSheets: "工作表",
    AuthDashboardPaneSize: "大小",
    AuthDashboardPaneTextZone: "文本",
    AuthDashboardPaneTiledButton: "平铺",
    AuthDashboardPaneTitleCheckbox: "显示仪表板标题",
    AuthDashboardPaneVerticalZone: "垂直",
    AuthDashboardPaneWebZone: "网页",
    AuthDashboardPaneZoneObjects: "对象",
    AuthFontFamilyAndSize: "{0} {1}",
    AuthFontListLoading: "正在加载...",
    AuthFormatLineVisibilityAutomatic: "自动",
    AuthFormatLineVisibilityOff: "关",
    AuthFormatLineVisibilityOn: "开",
    AuthFormatSectionCollapse: "更少",
    AuthFormatSectionExpand: "更多",
    AuthHeatmapIntensityLabel: "强度",
    AuthIncludeTotalsLabel: "包括合计",
    AuthLeftContentPaneLabel: "内容",
    AuthLeftLayoutPaneLabel: "布局",
    AuthLeftPaneLabelDashboard: "仪表板",
    AuthLeftPaneTabLabelAnalytics: "分析",
    AuthLineAutomaticPreview: "自动",
    AuthLineOffPreview: "关",
    AuthLineSizePixels: "{0} px",
    AuthMarkSizeLabel: "标记大小",
    AuthMarksCardChooseField: "更多字段",
    AuthMarksCardEncodingTooltipBasic: "在此处拖动维度或度量。",
    AuthMarksCardEncodingTooltipOptions: "在此处拖动维度或度量，或者单击获取更多选项。",
    AuthMastheadDone_Confirm_CanLogin: "是否要保存对工作簿进行的更改？<br><br>您需要登录才能完成保存更改。",
    AuthMastheadDone_Confirm_CanLogin_Confirm: "登录并保存",
    AuthMastheadDone_Confirm_CanLogin_Deny: "不保存",
    AuthMastheadDone_Confirm_CanSave: "是否要保存对工作簿进行的更改？",
    AuthMastheadDone_Confirm_CanSaveAs: "是否要在新的工作簿保存更改？",
    AuthMastheadDone_Confirm_CanSaveAs_Confirm: "保存副本...",
    AuthMastheadDone_Confirm_CanSaveAs_Deny: "不保存",
    AuthMastheadDone_Confirm_CanSave_Confirm: "保存",
    AuthMastheadDone_Confirm_CanSave_Deny: "不保存",
    AuthMastheadDone_Confirm_CanSave_Metrics: "是否要保存指标?",
    AuthMastheadDone_Confirm_Title: "保存工作簿",
    AuthMastheadDone_Confirm_Title_Metrics: "保存指标",
    AuthMastheadHelp: "帮助",
    AuthMastheadHelpSearch: "搜索帮助",
    AuthMastheadLogin: "登录",
    AuthMastheadLogout: "退出",
    AuthMastheadUserPrefs: "用户首选项",
    AuthMenuBarAnalysis: "分析",
    AuthMenuBarDashboard: "仪表板",
    AuthMenuBarData: "数据",
    AuthMenuBarExit: "关闭",
    AuthMenuBarFile: "文件",
    AuthMenuBarFormat: "设置格式",
    AuthMenuBarMap: "地图",
    AuthMenuBarStory: "故事",
    AuthMenuBarWindow: "窗口",
    AuthMenuBarWorksheet: "工作表",
    AuthMetricsSaveTitle: "保存指标",
    AuthNumberFormatDecimalLabel: "小数位数",
    AuthNumberFormatSeparatorLabel: "包括分隔符",
    AuthNumberFormatTypeAuto: "自动",
    AuthNumberFormatTypeCurrency: "货币",
    AuthNumberFormatTypeLabel: "数字类型",
    AuthNumberFormatTypeNumber: "数字",
    AuthNumberFormatTypePercentage: "百分比",
    AuthNumberFormatTypeScientific: "科学型",
    AuthNumberFormatUnitsBillionsEnglish: "十亿(B)",
    AuthNumberFormatUnitsBillionsStandard: "十亿(G)",
    AuthNumberFormatUnitsLabel: "单位",
    AuthNumberFormatUnitsMillions: "百万(M)",
    AuthNumberFormatUnitsNone: "无",
    AuthNumberFormatUnitsThousands: "千(K)",
    AuthOffLabel: "关",
    AuthOnLabel: "开",
    AuthPillRemove: "移除",
    AuthRenameDataSource: "重命名数据源",
    AuthRenameDatasourceError: "具有该名称的数据源已存在。请使用其他名称重试。",
    AuthRenameField: "重命名字段",
    AuthRenameObject: "重命名表",
    AuthRenameSheet: "重命名工作表",
    AuthRenameSheetError: "请将工作表重命名为新的唯一名称",
    AuthResetTooltip: "重置工具提示",
    AuthReverseColorLabel: "反向",
    AuthSaveButtonCancel: "取消",
    AuthSaveButtonSave: "保存",
    AuthSaveConfirmOverwrite: "{0} 是否覆盖?",
    AuthSaveErrorTitle: "保存时出错",
    AuthSaveLabelEmbedPassword: "嵌入数据源的密码",
    AuthSaveLabelName: "名称:",
    AuthSaveLabelProject: "项目:",
    AuthSaveLabelShowTabs: "将工作表显示为标签",
    AuthSaveTitle: "保存工作簿",
    AuthSaveWorkbookSavedMessage: "工作簿已保存",
    AuthSchemaViewerHeaderData: "数据",
    AuthSchemaViewerHeaderDimensions: "维度",
    AuthSchemaViewerHeaderFolders: "文件夹",
    AuthSchemaViewerHeaderMeaures: "度量",
    AuthSchemaViewerHeaderParameters: "参数",
    AuthSchemaViewerHeaderSets: "集",
    AuthSchemaViewerHeaderTables: "表",
    AuthSchemaViewerNoSearchMatches: "无匹配项",
    AuthSchemaViewerSearchPlaceholderText: "搜索",
    AuthSchemaViewerSearchToggleButtonLabel: "查找字段",
    AuthShowMeApply: "应用",
    AuthShowMeCantApply: "无法应用",
    AuthShowMeMultipleDimensions: "维度",
    AuthShowMeMultipleMeasures: "度量",
    AuthShowMeRecommended: "建议",
    AuthShowMeSingleDimension: "维度",
    AuthShowMeSingleMeasure: "度量",
    AuthSteppedColorLabel: "步骤",
    AuthStepsLabel: "步骤",
    AuthToolbarAddAllSubtotals: "添加所有小计",
    AuthToolbarCellSize: "单元格大小",
    AuthToolbarCellSizeBigger: "增大",
    AuthToolbarCellSizeNarrower: "变窄",
    AuthToolbarCellSizeShorter: "缩短",
    AuthToolbarCellSizeSmaller: "缩小",
    AuthToolbarCellSizeTaller: "增高",
    AuthToolbarCellSizeWider: "加宽",
    AuthToolbarCellTypeSquare: "方形",
    AuthToolbarCellTypeText: "文本",
    AuthToolbarDownloadWorkbook: "工作簿",
    AuthToolbarDownloadWorkbookErrorContent: "此工作簿包含未保存的更改。请保存所做的更改并重试。",
    AuthToolbarDownloadWorkbookErrorTitle: "无法下载工作簿",
    AuthToolbarExport: "下载",
    AuthToolbarFont: "字体",
    AuthToolbarFontDecrease: "减小字体大小",
    AuthToolbarFontIncrease: "增大字体大小",
    AuthToolbarFormatWorkbook: "设置工作簿格式",
    AuthToolbarMarkHideLabels: "隐藏标签",
    AuthToolbarMarkShowLabels: "显示标签",
    AuthToolbarMore: "更多",
    AuthToolbarPauseUpdates: "暂停更新",
    AuthToolbarRedo: "重做",
    AuthToolbarRemoveAllSubtotals: "移除所有小计",
    AuthToolbarResumeUpdates: "继续更新",
    AuthToolbarShare: "共享",
    AuthToolbarShowColumnGrandTotals: "显示行总和",
    AuthToolbarShowMe: "智能显示",
    AuthToolbarShowRowGrandTotals: "显示列总和",
    AuthToolbarSubscribe: "订阅",
    AuthToolbarSwap: "交换",
    AuthToolbarTotals: "合计",
    AuthToolbarUndo: "撤消",
    AuthToolbarWorksheet: "工作表",
    AuthToolbarZoomLevel: "适合",
    AuthWorkbookFormatPaneClear: "重置为默认值",
    AuthWorkbookFormatPaneClearOne: "清除",
    AuthWorkbookFormatPaneClearTooltip: "将上面的工作簿格式设置重置为其默认设置",
    AuthWorkbookFormatPaneCloseTooltip: "关闭格式设置窗格",
    AuthWorkbookFormatPaneTitle: "设置工作簿格式",
    AuthenticationRequired: "需要身份验证",
    AuthorBylineText: "请参见此作者提供的更多内容",
    AuthoringAutoRecoveredSessionMessage: "已恢复会话的初始工作簿编辑。若要保存所有编辑，请单击“文件”，然后单击“保存”或“另存为”。若要打开保存的工作簿，请单击“文件”，然后单击“恢复”。",
    AuthoringAutoRecoveredSessionMessageNoPublish: "已恢复会话的初始工作簿编辑。若要打开保存的工作簿，请单击“文件”，然后单击“恢复”。",
    AuthoringAutoRecoveredSessionMessageNoSave: "已恢复会话的初始工作簿编辑。若要保存所有编辑，请单击“文件”，然后单击“另存为”。若要打开保存的工作簿，请单击文件，然后单击“恢复”。",
    AuthoringAutoSavedRecoveredMessage: "以前的编辑已自动恢复。若要返回至已保存的工作簿，请单击“文件”，然后单击“恢复”。(来自于自动保存版本。恢复操作未实现。)",
    AuthoringLinePatternLabelDashed: "虚线",
    AuthoringLinePatternLabelDotted: "点划线",
    AuthoringLinePatternLabelSolid: "实线",
    AuthoringWorkbookTitle: "编辑 | {0}",
    AutomaticDashboardSizeText: "将调整仪表板大小以适合显示仪表板所在的任何屏幕",
    BaseClientAllAxisRanges: "所有轴范围",
    BaseClientAllChanges: "所有更改",
    BaseClientAllFilters: "所有筛选器",
    BaseClientAllSorts: "所有排序",
    BaseClientColumns: "列",
    BaseClientInvalidSheet: "无法显示工作表 \'{0}\' 的视图。该工作表无效。",
    BaseClientRows: "行",
    BaseClientSessionExpiredDialogMessage: "您的查看者会话已过期。您必须刷新浏览器。",
    BaseClientSessionExpiredDialogTitle: "会话已过期",
    BigQueryUseLegacySQLLabel: "使用旧版 SQL",
    BinColumnTableName: "数据桶",
    BrowserErrorProcessing: "浏览器处理错误",
    BrowserErrorProcessingMessage: "处理服务器响应时出错。",
    BrowserSecurityWarning: "通过 Internet Explorer 建立的连接不安全。若要继续，请切换到其他浏览器，或与 IT 管理员联系。",
    CalcColumnTableName: "计算",
    CalcEditorApply: "应用",
    CalcEditorApplyTooltip: "应用(Ctrl+Enter)",
    CalcEditorApplyTooltipMac: "应用(Cmd+Enter)",
    CalcEditorCalcError: "计算包含错误。",
    CalcEditorCalcOk: "计算有效。",
    CalcEditorDependenciesPrefix: "更改此计算可能会更改以下内容:",
    CalcEditorOkButtonTooltip: "应用并关闭",
    Cancel: "取消",
    CancelDialogCancellingStatus: "正在取消...",
    CancelDialogProcessingStatus: "正在处理...",
    ChromeDropdownButtonTooltip: "更多选项",
    ClearAliases: "清除别名",
    ClearAllButtonText: "清除列表",
    CloseDataSourceErrorDialogEpilogue: "确保这些工作表不再使用该数据源，然后重试。",
    CloseDataSourceErrorDialogMessage: "\'{0}\'数据源无法关闭，因为以下工作表正在使用它:",
    CloseDataSourceErrorDialogTitle: "无法关闭数据源",
    CloudConnectionWaitDialogSubtitle: "这可能需要几分钟",
    CloudConnectionWaitDialogSubtitleFilename: "正在加载 {0}。这可能需要几分钟。",
    CloudConnectionWaitDialogTitle: "正在连接...",
    CollapseSchemaPane: "折叠",
    CommentingToolbarButtonLabel: "注释",
    ConfirmationButtonConfirm: "是",
    ConfirmationButtonDeny: "否",
    ConfirmationTitle: "确认",
    ConnectToCloudFileWindowTitle: "连接到 {0}",
    ConnectToData: "连接到数据",
    ConnectionDialogSubtitleConnect: "选择现有数据源以从其开始。",
    ConnectionDialogSubtitleCreateAndConnect: "从头开始创建新的数据源或选择现有数据源以从其开始。",
    ConnectionDialogSubtitleCreateNewConnection: "添加新连接以创建跨数据库联接。",
    ConnectionMissingFileDialogMissingDirectoryText: "目录丢失或已被移动:<br>{0}<br>是否将其替换为另一个文件?",
    ConnectionMissingFileDialogText: "无法找到引用的文件: {0}。<br>是否将该文件替换为其他文件?",
    ConnectionMissingFileDialogTitle: "缺少文件",
    ConnectorDetailBackButton: "后退",
    CreateAreaAnnotationFromVizContextMenu: "注释区域...",
    CreateConnectionBadPasswordError: "用户名或密码无效。请检查数据库名称和凭据，然后重试。",
    CreateConnectionErrorHeader: "无法连接到 {0}",
    CreateConnectionExcelAndText: "Excel 和文本",
    CreateConnectionOnTableauServer: "在此站点上",
    CreateConnectionPublishedDatasources: "已发布数据源",
    CreateConnectionToAFile: "文件",
    CreateConnectionToDatabase: "连接器",
    CreateMarkAnnotationFromVizContextMenu: "注释标记...",
    CreatePointAnnotationFromVizContextMenu: "注释点...",
    CurrentPagePanelShowHistory: "显示历史记录",
    CurrentSubscribers: "当前订阅者",
    CustomPaletteGroupUnselectedNote: "选择了自定义调色板。如果选择其他调色板，您将无法再次为此视图选择此自定义调色板。",
    CustomViewsAddYourOwnCustomView: "添加自己的自定义视图",
    CustomViewsCancel: "取消",
    CustomViewsCannotChangeDefault: "不能将默认设置更改为未列出的自定义视图",
    CustomViewsChangeDefaultTo: "将默认设置更改为“{0}”",
    CustomViewsCurrentDefaultIs: "当前默认设置为“{0}”",
    CustomViewsDialogTitle: "自定义视图",
    CustomViewsDone: "完成",
    CustomViewsManageCustomViews: "管理自定义视图",
    CustomViewsManageHeader: "共享、重命名和删除我的自定义视图",
    CustomViewsMyCustomViews: "我的自定义视图",
    CustomViewsNameYourCustomView: "命名自定义视图",
    CustomViewsOriginalName: "原始名称: \"{0}\"",
    CustomViewsOriginalView: "原始",
    CustomViewsOtherCustomViews: "其他自定义视图",
    CustomViewsRemember: "记住",
    CustomViewsRememberMyChanges: "记住我的更改",
    CustomViewsSelectCustomView: "选择自定义视图",
    CustomViewsStartManage: "管理自定义视图",
    CustomViewsUndo: "撤消",
    CustomViewsUnlistedCustomView: "未列出的自定义视图",
    DashboardAuthZoneHeightDisplay: "高度 {0}",
    DashboardAuthZoneLeftPositionDisplay: "x {0}",
    DashboardAuthZoneTopPositionDisplay: "y {0}",
    DashboardAuthZoneWidthDisplay: "宽度 {0}",
    DashboardAuthoringCustomSizeName: "自定义",
    DashboardAuthoringDeviceLayoutDefault: "默认值",
    DashboardAuthoringDeviceLayoutDesktop: "桌面",
    DashboardAuthoringDeviceLayoutPhone: "电话",
    DashboardAuthoringDeviceLayoutTablet: "平板电脑",
    DashboardAuthoringHeightSpinnerLabel: "高度",
    DashboardAuthoringMaximumSizeLabel: "最大值",
    DashboardAuthoringMinimumSizeLabel: "最小值",
    DashboardAuthoringWidthSpinnerLabel: "宽度",
    DashboardButtonAccessDenied: "拒绝访问",
    DashboardButtonNoPermissions: "您没有查看链接的内容的权限。",
    DashboardGridSize: "网格大小(像素)",
    DashboardSpacingNone: "无",
    DataAlertAccessErrorMessage: "视图“{0}”已更改，您尝试访问的通知不再有效。",
    DataAlertAccessErrorTitle: "访问通知时出错",
    DataAlertAddMeFailureToast: "无法将您添加到此通知的收件人。",
    DataAlertAddMeInvalidEmailAddressFailureToast: "无法将您添加到此通知的收件人。若要接收通知，请将电子邮件地址添加到您的 Tableau 帐户设置中。",
    DataAlertAddMeSuccessToast: "已将您添加到“{0}”。",
    DataAlertChangeOwnerFailureToast: "无法更改此通知的所有者。",
    DataAlertChangeOwnerSuccessToast: "通知的所有者已更改。",
    DataAlertCondition: "条件",
    DataAlertCreateButton: "创建通知",
    DataAlertCreateButtonSaving: "正在保存...",
    DataAlertCreateFailure: "未能创建通知。",
    DataAlertCreateSuccess: "已成功创建通知。",
    DataAlertDatasourceError: "无法创建通知，因为此工作簿使用需要密码的数据源。",
    DataAlertDeleteButtonResumeError: "删除通知",
    DataAlertDeleteConfirmation: "是否永久删除通知“{0}”? 此通知有 {1} 个接收者。",
    DataAlertDeleteConfirmationToast: "已删除“{0}”。",
    DataAlertDeleteFailureToast: "无法删除此通知。",
    DataAlertDialogTitle: "创建通知",
    DataAlertDialogTitleEditMode: "编辑通知",
    DataAlertDisplayAlertFailureToast: "未能显示通知“{0}”。",
    DataAlertEditFailureToast: "无法编辑此通知。",
    DataAlertErrorDialogTitle: "编辑通知时出错",
    DataAlertErrorDialogViewChanged: "视图“{0}”已更改，您尝试编辑的通知不再有效。",
    DataAlertErrorDialogViewChangedWithSubject: "视图“{0}”已更改，通知“{1}”不再有效。",
    DataAlertInitFailure: "无法生成通知创建对话框。",
    DataAlertInvalidPluralUsers: "无法通知 {0} 个用户。",
    DataAlertInvalidUser: "无法通知 1 个用户。",
    DataAlertLoadCustomizedViewFailure: "无法加载自定义视图",
    DataAlertLoadForEditFailure: "无法加载数据通知以进行编辑。",
    DataAlertNoSubjectErrorMessage: "输入通知电子邮件的主题",
    DataAlertNoUsersMatchSearch: "没有用户符合此搜索条件",
    DataAlertNotificationInterval: "当条件为真时，发送电子邮件:",
    DataAlertOnConstantThreshold: "发送电子邮件，条件是任何条形的“{0}”:",
    DataAlertOnConstantThreshold2: "发送电子邮件，条件是“{0}”:",
    DataAlertPublicCheckboxLabel: "使其他用户可查看",
    DataAlertPublicInfo: "具有视图访问权限的任何人都可查看此通知并将自己添加到其中。",
    DataAlertRecipientPillNoDownloadPermissions: "{0} 没有下载权限。",
    DataAlertRecipientPillNoEmail: "{0} 在 Tableau 中没有有效的电子邮件地址。",
    DataAlertRecipientPillNoViewPermissions: "{0} 没有查看权限。",
    DataAlertRecipientPillUnlicensed: "{0} 是未许可用户，并且没有查看权限。",
    DataAlertRecipientWithNoEmail: "用户必须在 Tableau 中具有电子邮件地址，然后才能将其添加为接收者",
    DataAlertRecipients: "接收者",
    DataAlertRemoveMeFailureToast: "无法将您从此通知的收件人中移除。",
    DataAlertRemoveMeSuccessToast: "已将您从 {0} 中移除",
    DataAlertResumeErrorDialogTitle: "恢复通知时出错",
    DataAlertResumedFailureToast: "数据通知未能恢复",
    DataAlertResumedSucessfullyToast: "数据通知成功恢复",
    DataAlertShowFailureToast: "无法访问此通知。",
    DataAlertSubject: "主题",
    DataAlertSubjectTemplate: "数据通知 - {0}",
    DataAlertThreshold: "阈值",
    DataAlertThresholdConditionMet: "当前条件为真",
    DataAlertThresholdConditionUnmet: "当前条件不为真",
    DataAlertThresholdErrorDouble: "值必须为数值",
    DataAlertThresholdErrorGeneric: "值必须为数值",
    DataAlertThresholdErrorIntegerInputDouble: "值不能包含小数",
    DataAlertThresholdErrorIntegerInputNonNumeric: "值必须为整数",
    DataAlertToolbarButtonLabel: "通知",
    DataAlertUpdateButton: "保存通知",
    DataAlertUpdateFailure: "未能更新通知。",
    DataAlertUpdateSuccess: "已成功更新通知。",
    DataAlertsRecipientsSearchPlaceholder: "接收者姓名或用户名",
    DataDetailsToolbarButtonLabel: "Data Details",
    DataGridCancelButton: "取消",
    DataGridErrorButton: "取消",
    DataGridErrorText: "出现了错误。",
    DataGridLoadingText: "正在加载数据...",
    DataGridNullKeyword: "Null",
    DataGridUndefinedKeyword: "未定义",
    DataGridUpdateButton: "立即更新",
    DataGridZeroRowsText: "无数据",
    DataInterpreterDataLoss: "数据解释器移除了一些数据。",
    DataInterpreterDescription: "数据解释器或许可以清理您的 {0} 工作簿。",
    DataInterpreterFinished: "已使用数据解释器清理",
    DataInterpreterLoading: "正在加载...",
    DataInterpreterReady: "使用数据解释器",
    DataInterpreterUndo: "若要撤消更改，请清除复选框。",
    DataLineageToolbarButtonLabel: "世系",
    DataSourceConnectionDriverNotInstalledErrorMessage: "连接到数据源所需的驱动程序未安装。请与 Tableau Server 管理员联系。",
    DataSourceConnectionErrorMessage: "连接到数据源时出错。数据源可能已损坏或无效。",
    DataSourceConnectionErrorTitle: "无法连接到数据源",
    DataSourceConnectionErrorTitleText: "连接到数据源“{0}”时出现问题。请尝试编辑该数据源。",
    DataSourceCreationInProgress: "正在创建数据源",
    DataSourceGenericErrorButtonLabel: "重试",
    DataSourceGenericErrorMsg: "无法连接到数据源。",
    DataSourceGenericErrorSubMsg: "请再次尝试连接。如果问题仍然存在，请断开数据源连接并与数据源所有者联系。",
    DataSourceGenericTitle: "数据源错误",
    DataTabAddConnectionToDatasource: "添加",
    DataTabCloseConnection: "移除",
    DataTabConnectionsHeader: "连接",
    DataTabCreateJoinCalculation: "创建联接计算...",
    DataTabCustomSqlTitle: "自定义 SQL",
    DataTabDataGridButtonTooltip: "预览数据源",
    DataTabEditConnection: "编辑连接...",
    DataTabEditDialogTitle: "联接",
    DataTabEditJoinAddJoinPlaceholder: "添加新的联接子句",
    DataTabEditJoinCalculation: "编辑联接计算...",
    DataTabEditJoinClauseHeaderTitle: "数据源",
    DataTabEditJoinClauseRemoveTooltip: "删除联接子句",
    DataTabEditJoinDisabledTooltip: "此联接类型不适用于这种连接。",
    DataTabEditJoinFull: "完全外部",
    DataTabEditJoinFullTooltip: "包括两个表中的所有值。没有匹配项的成员将显示为 null。",
    DataTabEditJoinInner: "内部",
    DataTabEditJoinInnerTooltip: "只包含在两个表中具有匹配项的值。",
    DataTabEditJoinLeft: "左侧",
    DataTabEditJoinLeftTooltip: "包括左侧表中的所有成员和右侧表中的所有匹配项。没有匹配项的成员将在右侧显示为 null。",
    DataTabEditJoinRight: "右侧",
    DataTabEditJoinRightTooltip: "包括右侧表中的所有成员和左侧表中的所有匹配项。没有匹配项的成员将在左侧显示为 null。",
    DataTabFilePropertiesCharset: "字符集:",
    DataTabFilePropertiesLocale: "区域设置:",
    DataTabFilePropertiesQualifier: "文本限定符:",
    DataTabFilePropertiesSeparator: "字段分隔符:",
    DataTabFilterInfoLabel: "筛选器",
    DataTabInitialSql: "初始 SQL...",
    DataTabJoinOnCalculationCaption: "联接计算",
    DataTabLiveExtractLabel: "连接",
    DataTabMetadataGridButtonTooltip: "管理元数据",
    DataTabName: "数据源",
    DataTabNewCustomSqlLabel: "新自定义 SQL",
    DataTabNewCustomSqlTooltip: "创建新的自定义 SQL 查询",
    DataTabNewUnionLabel: "新建并集",
    DataTabNewUnionTooltip: "添加新并集",
    DataTabQualifierAutomatic: "自动",
    DataTabQualifierNone: "无",
    DataTabRenameConnection: "重命名",
    DataTabRenameConnectionTitle: "重命名连接",
    DataTabSchemaReadOnlyNoneSelected: "未选择 {0}。",
    DataTabSchemaSlowMetadataNoneSelected: "选择 {0}",
    DataTabSearchContains: "包含",
    DataTabSearchCountEntityNoMatch: "无匹配项",
    DataTabSearchCountEntityResult: "找到 {0} 个匹配项",
    DataTabSearchEntityCheckPermissions: "检查权限",
    DataTabSearchEntityCountLoading: "正在计数...",
    DataTabSearchEntityFetchLoading: "正在获取结果....",
    DataTabSearchEntityLoadButton: "加载",
    DataTabSearchExact: "精确",
    DataTabSearchFilter: "搜索",
    DataTabSearchStartsWith: "开头为",
    DataTabSeparatorComma: "逗号",
    DataTabSeparatorOther: "其他",
    DataTabSeparatorSemicolon: "分号",
    DataTabSeparatorSpace: "空格",
    DataTabSeparatorTab: "制表符",
    DataTabSeparatorVerticalBar: "垂直条",
    DataTabStoredProceduresHeader: "存储过程",
    DataTabStoredProceduresNotAllowed: "存储过程对于多连接数据源不可用。",
    DataTabStoredProceduresPlaceHolder: "输入存储过程名称",
    DataTabStoredProceduresWithParamsNotAvailable: "您无法运行包含参数的存储过程。",
    DataTabStoredProceduresWithParamsNotAvailableTitle: "无法运行",
    DataTabTablesSlowMetadataNotSupported: "当前不支持表选择。",
    DataTabUnionApplyLabel: "应用",
    DataTabUnionConnectionNameLabel: "连接: ",
    DataTabUnionDifferentConnectionWarning: "您只能合并来自同一连接的数据",
    DataTabUnionDragRegionLabel: "将表拖至并集",
    DataTabUnionDragTables: "将表拖到此处",
    DataTabUnionInvalidPillTooltip: "Tableau 找不到或无法识别此表。请移除或替换表",
    DataTabUnionOKLabel: "确定",
    DataTabUnionTablesLabel: "并集中的表: ",
    DataTabViewDataCancel: "取消",
    DataTabViewDataCanceling: "正在取消...",
    DataTabViewDataDialogTitle: "查看数据: {0}",
    DataTabViewDataGetDataButtonTooltip: "获取数据",
    DataTabViewDataLoadingRows: "正在加载行...",
    DataTabViewDataProcessingRows: "正在处理行...",
    DataTabViewDataTooltip: "查看数据",
    December: "十二月",
    DecemberShort: "十二月",
    DeleteAnnotationFromVizContextMenu: "删除注释",
    DeleteSelectedAnnotationFromVizContextMenu: "删除所选注释",
    DeleteSheetWithVizInTooltipDialogButton: "删除工作表",
    DeleteSheetWithVizInTooltipDialogMessage: "此工作表显示在其他工作表的工具提示中。删除此工作表也会将其从那些工具提示中移除。<br><br>是否确实要将其删除?",
    DeleteSheetWithVizInTooltipDialogTitle: "删除工作表",
    DeviceLayoutSelectorConfirmPromptDesktopLayoutMessage: "是否切换到台式机布局?",
    DeviceLayoutSelectorConfirmPromptPhoneLayoutMessage: "是否切换到手机布局?",
    DeviceLayoutSelectorConfirmPromptTabletLayoutMessage: "是否切换到平板电脑布局?",
    DeviceLayoutSelectorConfirmPromptTitle: "更改设备布局",
    DeviceLayoutSelectorDesktopLayoutToolbarButtonLabel: "台式机布局",
    DeviceLayoutSelectorPhoneLayoutToolbarButtonLabel: "手机布局",
    DeviceLayoutSelectorTabletLayoutToolbarButtonLabel: "平板电脑布局",
    DialogButtonCancel: "取消",
    DialogButtonDownload: "下载",
    DialogButtonExport: "生成",
    DialogButtonOK: "确定",
    DialogButtonReset: "重置为原始字段名称",
    DialogNoButtonText: "否",
    DialogYesButtonText: "是",
    DisabledDataTabTooltipDetails: "选择另一个数据源，或者下载此工作簿，然后使用 Tableau Desktop 打开。",
    DisabledDataTabTooltipInfo: "无法从数据源页面中查看当前数据源。",
    DownloadAsVersionDialogDownloadButton: "下载",
    DownloadAsVersionDialogHelpLink: "了解更多信息",
    DownloadAsVersionDialogTitle: "下载 Tableau 工作簿",
    DownloadAsVersionDialogWarning: "选择要将工作簿下载为的版本。使工作簿保持其当前版本或选择不同的版本。如果您将工作簿降级为以前的版本，则某些功能可能会丢失。",
    DownloadAsVersionDropdownDefaultLabel: "当前",
    DownloadAsVersionDropdownLabel: "版本",
    DownloadDialogDownloadAsVersionButton: "以版本形式下载",
    DragAndDropAFileOrUploadFromComputer_Part1: "拖放文件",
    DragAndDropAFileOrUploadFromComputer_Part2: "或",
    DragAndDropAFileOrUploadFromComputer_Part3: "从计算机上载",
    DragAndDropError_Multi: "不允许上载多个文件。请改为上载单个文件，再试一次。",
    DragAndDropError_Title: "无法上载文件",
    DropFieldHintText: "在此处放置字段",
    EditAnnotationFromVizContextMenu: "编辑注释",
    EditConnectionDialogTitle: "编辑连接",
    EditConnectionInformationDialogText: "连接到数据源“{0}”时出现问题。<br>是否要编辑连接信息?",
    EditConnectionInformationDialogTitle: "编辑连接",
    EditDataExplanation: "选择发布的数据源以对其进行编辑。",
    EmptyDashboardMessage: "在此处添加工作表",
    EmptyDashboardSubMessage: "从左侧的列表中拖放或双击。",
    EmptyFloatingLayoutMessage: "将工作表拖到此处",
    EmptyImageZoneMessage: "从对象菜单中选择一个图像。",
    EnterFullscreen: "全屏",
    ExitFullscreen: "退出全屏",
    ExpandSchemaPane: "展开",
    ExportCrosstabDialogMessage: "已生成交叉表。",
    ExportCrosstabDialogTitle: "下载交叉表",
    ExportDataDialogMessage: "已生成数据。",
    ExportDataDialogTitle: "下载数据",
    ExportImageDialogMessage: "已生成图像。",
    ExportImageDialogTitle: "下载图像",
    ExportPowerPointDialogMessage: "已生成 PowerPoint 文件。",
    ExportPowerPointDialogTitle: "下载 PowerPoint",
    ExtensionBlockedByServer: "服务器管理员将扩展程序({0}，{1})放在阻止列表中以防止该扩展程序运行。请与服务器管理员联系以了解详细信息。",
    ExtensionBlockedPreRelease: "“{1} 的版本 {0} 正在使用 Tableau Extensions API 的预发行版本。使用 Tableau Extensions API 预发行版的扩展程序只支持在 Tableau 的预发行版上使用。若要获取可与 Tableau 发行版配合使用的此扩展程序的版本，请通过 {2} 与扩展程序开发人员联系。”",
    ExtensionDeniedByUser: "扩展程序由于没有运行权限而无法工作。可通过刷新页面来重置权限。",
    ExtensionDeniedByUserAuthoring: "扩展程序由于没有运行权限而无法工作。可通过上下文菜单来重置权限。",
    ExtensionNotFoundOnSafelist: "{0} 扩展程序(url: {1})不在此站点的安全列表上，因此不允许运行。请与{2}联系以将此扩展程序添加到安全列表。",
    ExtensionViolatesSafelistPermission: "{0} 扩展程序(url: {1})需要访问完整数据，但在站点设置中未被授予访问完整数据的权限。请与{2}联系，更改扩展程序的数据访问设置。",
    ExtensionsDisabledOnPublic: "Tableau Public 上不支持扩展程序。",
    ExtensionsDisabledOnServer: "此服务器上不允许扩展程序。请与服务器管理员联系，更改此设置以允许扩展程序。",
    ExtensionsDisabledOnSite: "此站点上不允许扩展程序。请与{0}联系，更改此站点设置以允许扩展程序。",
    February: "二月",
    FebruaryShort: "二月",
    FieldNameLabel: "字段名称:",
    FieldNameResetErrorMessage: "无法将“{0}”重置为其默认({1})名称，因为工作簿中的另一个字段现在具有该名称。",
    FieldNameResetErrorTitle: "无法重置字段名称",
    FieldRenameError: "名为“{0}”的字段已存在。",
    FieldRenameErrorDialogTitle: "无法重命名字段",
    FileSingleUploadTitle: "正在上载文件",
    FileUploadAccessError: "无法访问文件，因为该文件可能已打开或已锁定进行编辑。请关闭文件并重试。",
    FileUploadAccessError_Title: "无法打开文件",
    FileUploadButtonAdd: "添加",
    FileUploadButtonCancel: "取消",
    FileUploadButtonClose: "关闭",
    FileUploadButtonLess: "更少",
    FileUploadButtonMore: "更多",
    FileUploadButtonReplaceUpdate: "替换和更新",
    FileUploadButtonRetry: "重试",
    FileUploadButtonSkipPlural: "跳过文件并开始上载",
    FileUploadButtonSkipSingular: "跳过文件并开始上载",
    FileUploadConnectionCreationErrorReason: "无法依据上载的文件创建连接。请上载其他文件，然后重试。",
    FileUploadConnectionCreationErrorTitle: "无法连接到上载的文件",
    FileUploadConnectionCreationMultiErrorTitle: "无法连接到一些上载的文件",
    FileUploadDSCreationErrorReason: "无法依据上载的文件创建数据源。请上载其他文件，然后重试。",
    FileUploadDSCreationErrorTitle: "未创建数据源",
    FileUploadDSErrorTitleMultiFailed: "数据源错误",
    FileUploadDropToUploadInstructions: "拖放以上载",
    FileUploadErrorInfosCompletedHeader: "已完成",
    FileUploadErrorInfosFailedHeader: "失败",
    FileUploadErrorTitle: "上载失败",
    FileUploadErrorTitleMultiComplete: "上载完成: {0}",
    FileUploadErrorTitleMultiFailed: "上载失败: {0}",
    FileUploadFailureIgnoreAndContinueLabel: "忽略并继续",
    FileUploadFailureTextPlural: "上载 {0} 个文件失败",
    FileUploadFailureTextSingular: "{0} 上载失败",
    FileUploadFatalErrorFileExists: "您正在上载的文件与当前正在使用的文件具有相同文件名。您是想替换和更新现有的文件，还是用新名称添加此文件?",
    FileUploadFatalErrorFileIsEmptySubtitle: "此文件为空。请使用不同的文件再试一次。",
    FileUploadFatalErrorFileIsTooBigSubtitle: "文件太大。最大大小: {0}",
    FileUploadFatalErrorSameFileTitle: "相同文件名",
    FileUploadFatalErrorTitle: "无法上载文件",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_a_a: "{0} 不能被 {1} 替换。改为上载 {0}，再试一次。",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_a_an: "{0} 不能被 {1} 替换。改为上载 {0}，再试一次。",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_an_a: "{0} 不能被 {1} 替换。改为上载 {0}，再试一次。",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_an_an: "{0} 不能被 {1} 替换。改为上载 {0}，再试一次。",
    FileUploadFatalErrorUnsupportedFileTypeSubtitle: "Web 上当前不支持此文件类型。若要使用此类型的文件，请从 Tableau Desktop 连接到该文件，然后将其发布到服务器。",
    FileUploadFileTypeAccess: "Access",
    FileUploadFileTypeExcel: "Excel",
    FileUploadFileTypeExcelFile: "Excel 文件",
    FileUploadFileTypeJson: "JSON 文件",
    FileUploadFileTypeOther: "其他文件",
    FileUploadFileTypeSpatial: "空间文件",
    FileUploadFileTypeStatistical: "统计文件",
    FileUploadFileTypeText: "文本文件",
    FileUploadFinishedTitle: "完成",
    FileUploadPreProcessingTitle: "正在准备文件",
    FileUploadProcessingTitle: "正在处理 {0} 个文件",
    FileUploadProgressIndicator: "已上载 {0} {2} 个，共 {1} {2} 个",
    FileUploadServerUnresponsive: "服务器无响应",
    FileUploadTitle: "正在上载 {0} 个文件",
    FileUploadUploadErrorReason: "未上载文件。",
    Filter: "筛选器",
    FindAllButtonLabel: "查找全部",
    FindContains: "包含",
    FindExactMatch: "精确匹配",
    FindInRangeAll: "(全部)",
    FindInRangeLabel: "查找范围:",
    FindLabel: "查找:",
    FindNextButtonLabel: "查找下一个",
    FindStartsWith: "开头为",
    FindTextPlaceHolder: "搜索",
    FirstEnding: "第 {0}",
    Friday: "星期五",
    FridayShort: "周五",
    FunctionTypeAggregate: "聚合",
    FunctionTypeAll: "全部",
    FunctionTypeClearTooltip: "清除",
    FunctionTypeDate: "日期",
    FunctionTypeLogical: "逻辑",
    FunctionTypeNumber: "数字",
    FunctionTypeSearchHint: "输入要搜索的文本",
    FunctionTypeString: "字符串",
    FunctionTypeTableCalculation: "表计算",
    FunctionTypeType: "类型",
    FunctionTypeUser: "用户",
    GlassPaneLoading: "正在加载...",
    GlassPaneSessionExpired: "会话已过期",
    GlassPaneUpdating: "正在更新...",
    GoToSheet: "转到工作表",
    GotoMyLocationPermissionDeniedError: "Tableau 无权使用您的位置。请检查您的位置设置，然后重试。",
    GotoMyLocationPermissionDeniedUnsecureConnection: "Tableau 无权使用您的位置。请检查您的位置设置，然后验证您是否正在使用安全 (https) 连接。",
    GotoMyLocationPositionUnavailableError: "Tableau 找不到您的位置。请检查 Internet 连接，然后重试。",
    GotoMyLocationTimeoutError: "我们尝试查找您的位置的操作已超时。",
    GotoMyLocationTooltip: "转到我的位置",
    GridDialogTitle: "网格选项",
    GroupColumnTableName: "分组",
    GroupDialogGroupButtonLabel: "分组",
    GroupDialogHideFindOptions: "隐藏选项",
    GroupDialogLargeDomainWarning: "分组功能由于此列的域大小过大而已禁用。",
    GroupDialogRenameButtonLabel: "重命名",
    GroupDialogShowFindOptions: "显示选项",
    GroupDialogUngroupButtonLabel: "取消分组",
    GroupsLabel: "群组:",
    HelpMenuItemAllHelpTopics: "打开已安装的帮助",
    HelpMenuItemContactSupport: "支持",
    HelpMenuItemGetHelpAndSupport: "获取帮助与支持",
    HelpMenuItemWebAuthor: "Web 制作帮助",
    HelpMenuItemWebAuthor1: "谁可以编辑和创建工作簿",
    HelpMenuItemWebAuthor2: "编辑和创建视图",
    HelpMenuItemWebAuthor3: "创建工作簿并生成视图",
    HideDetailsLabel: "隐藏详细信息",
    Hour: "小时",
    Hours: "{0} 小时",
    IncludeOtherLabel: "包括“其他”",
    January: "一月",
    JanuaryShort: "一月",
    July: "七月",
    JulyShort: "七月",
    June: "六月",
    JuneShort: "六月",
    KeyboardShortcutTriggerKeyArrowDown: "向下箭头",
    KeyboardShortcutTriggerKeyArrowLeft: "向左箭头",
    KeyboardShortcutTriggerKeyArrowRight: "向右箭头",
    KeyboardShortcutTriggerKeyArrowUp: "向上箭头",
    KeyboardShortcutTriggerKeyEnter: "Enter",
    KeyboardShortcutTriggerKeyF1: "F1",
    KeyboardShortcutTriggerKeyF11: "F11",
    KeyboardShortcutTriggerKeyF12: "F12",
    KeyboardShortcutTriggerKeyF2: "F2",
    KeyboardShortcutTriggerKeyForwardSlash: "/",
    KeyboardShortcutTriggerKeyMacArrowDown: "↓",
    KeyboardShortcutTriggerKeyMacArrowLeft: "←",
    KeyboardShortcutTriggerKeyMacArrowRight: "→",
    KeyboardShortcutTriggerKeyMacArrowUp: "↑",
    KeyboardShortcutTriggerKeyMacEnter: "↵",
    LayoutPaneArrangeSectionTitle: "排列",
    LayoutPaneBackgroundColorTitle: "背景",
    LayoutPaneBorderButtonTitle: "边界",
    LayoutPaneFloatingCheckbox: "浮动",
    LayoutPaneHSizeSpinner: "高",
    LayoutPaneMarginButtonTitle: "外边距",
    LayoutPanePaddingButtonTitle: "内边距",
    LayoutPanePositionSpinnersTitle: "位置",
    LayoutPaneSelectedItemTitle: "选定项",
    LayoutPaneSizeSpinnersTitle: "大小",
    LayoutPaneSpacingAllSidesEqual: "所有方面都相等",
    LayoutPaneSpacingBottom: "底部",
    LayoutPaneSpacingLeft: "左侧",
    LayoutPaneSpacingRight: "右侧",
    LayoutPaneSpacingTop: "顶部",
    LayoutPaneWSizeSpinner: "宽",
    LayoutPaneXPositionSpinner: "x",
    LayoutPaneYPositionSpinner: "y",
    LayoutPaneZoneTitleCheckbox: "显示标题",
    LayoutTreeSectionTitle: "项分层结构",
    LeftPaneDSDWarningMsg: "无法在 Web 上编辑设备布局。若要进行编辑，请在 Tableau Desktop 上打开工作簿。",
    LegacyPaletteUnselectedNote: "已停止使用此调色板。如果选择其他调色板，您将无法再次选择此调色板。",
    Legend: "图例",
    LegendPanelHighlightSelectedItems: "突出显示选定项",
    LinePatternNone: "无",
    LineTypeHeading: "行类型",
    ListLengthFive: "{0}、{1}、{2}、{3} 和 {4}",
    ListLengthFour: "{0}、{1}、{2} 和 {3}",
    ListLengthSeven: "{0}、{1}、{2}、{3}、{4}、{5} 和 {6}",
    ListLengthSix: "{0}、{1}、{2}、{3}、{4} 和 {5}",
    ListLengthThree: "{0}、{1} 和 {2}",
    ListLengthTwo: "{0} 和 {1}",
    LogOnButton: "登录以继续",
    ManageCustomViewsDisabledExplanation: "没有要管理的自定义视图。",
    ManageSubscriptions: "管理",
    MapAutoDrillCheckBox: "启用自动钻取",
    MapFloatingToolbarVizCheckBox: "显示视图工具栏",
    MapGeoSearchVizCheckBox: "显示地图搜索",
    MapOptionsDialogTitle: "地图选项",
    MapOptionsDropDownLabel: "单位:",
    MapOptionsUnitAutomatic: "自动",
    MapOptionsUnitMetric: "公制",
    MapOptionsUnitUS: "美制",
    MapScaleVizibilityCheckBox: "显示地图比例尺",
    MapVizNavCheckBox: "允许平移和缩放",
    MapsSearchViewClearInputTooltip: "清除搜索",
    MapsSearchViewInitialText: "搜索地图",
    March: "三月",
    MarchShort: "三月",
    MarkTextOneMark: "{0} 个标记",
    MarksTextMultiMark: "{0} 个标记",
    May: "五月",
    MayShort: "五月",
    MenuBackButton: "后退",
    MessageCharacterLimit: "{0} 个字符，共 {1} 个",
    MetaDataGrid_ConnectionColor: "连接颜色",
    MetaDataGrid_DataType: "数据类型",
    MetaDataGrid_FieldName: "字段名称",
    MetaDataGrid_RemoteFieldName: "远程字段名称",
    MetaDataGrid_Table: "表",
    Minutes: "{0} 分钟",
    ModifierKeyWithDelimiterHintTextAlt: "Alt+",
    ModifierKeyWithDelimiterHintTextCommand: "⌘",
    ModifierKeyWithDelimiterHintTextControl: "Ctrl+",
    ModifierKeyWithDelimiterHintTextMacControl: "⌃",
    ModifierKeyWithDelimiterHintTextMacOption: "⌥",
    ModifierKeyWithDelimiterHintTextMacShift: "⇧",
    ModifierKeyWithDelimiterHintTextShift: "Shift+",
    ModifierKeyWithDelimiterHintTextWindows: "Win+",
    Monday: "星期一",
    MondayShort: "周一",
    MoreActions: "更多操作",
    NewDashboardName: "新建仪表板",
    NewDataSource: "新建数据源",
    NewStoryName: "新建故事",
    NewWorksheetName: "新建工作表",
    NotificationIntervalDaily: "最多每天一次",
    NotificationIntervalEveryTime: "尽可能频繁",
    NotificationIntervalHourly: "最多每小时一次",
    NotificationIntervalOnlyOnce: "一次 - 首次为真时",
    NotificationIntervalWeekly: "最多每周一次",
    November: "十一月",
    NovemberShort: "十一月",
    NumberEnding: "第 {0}",
    NumericBinsBinSizeLabel: "数据桶大小:",
    NumericBinsCntDLabel: "不同计数:",
    NumericBinsDiffLabel: "差异:",
    NumericBinsFieldNameLabel: "新字段名称: ",
    NumericBinsMaxLabel: "最大值:",
    NumericBinsMinLabel: "最小值:",
    NumericBinsRangeOfValuesLabel: "值范围:",
    OAuthReauthenticateButton: "登录",
    OAuthReauthenticateMessage: "如果无法连接，请与您的 Tableau 管理员联系。",
    OAuthReauthenticateTitle: "您需要再次登录。",
    October: "十月",
    OctoberShort: "十月",
    OldGroupWarning: "该组是在旧版本的 Tableau 中创建的，无法在计算中使用。 ",
    OldGroupWarningLink: "创建副本。",
    OpenInTableauMobile: "在 Tableau Mobile 中打开",
    OperatorAbove: "高于",
    OperatorAboveOrEqual: "高于或等于",
    OperatorBelow: "低于",
    OperatorBelowOrEqual: "低于或等于",
    OperatorEqual: "等于",
    PanZoomSelectToolsAppendTooltip: "添加到所选内容",
    PanZoomSelectToolsCloseButtonTooltipMobile: "退出选择模式",
    PanZoomSelectToolsLassoSelectionTooltip: "套索(D)",
    PanZoomSelectToolsLassoSelectionTooltipMobile: "套索选择",
    PanZoomSelectToolsPanTooltip: "平移(F)",
    PanZoomSelectToolsPanTooltipMobile: "平移",
    PanZoomSelectToolsRadialSelectionTooltip: "径向(S)",
    PanZoomSelectToolsRadialSelectionTooltipMobile: "径向选择",
    PanZoomSelectToolsRectangularSelectionTooltip: "矩形(A)",
    PanZoomSelectToolsRectangularSelectionTooltipMobile: "矩形选区",
    PanZoomSelectToolsZoomAreaTooltip: "缩放区域(Z)",
    PanZoomSelectToolsZoomHomeTooltip: "缩放主页",
    PanZoomSelectToolsZoomInTooltip: "放大(双击)",
    PanZoomSelectToolsZoomOutTooltip: "缩小(Shift+双击)",
    PdfDialogClearAll: "全部清除",
    PdfDialogContentStory: "本故事",
    PdfDialogCreatePdf: "创建 PDF",
    PdfDialogOrientation: "方向",
    PdfDialogPaperSize: "纸张尺寸",
    PdfDialogScalingLabel: "缩放",
    PdfDialogSelectAll: "全选",
    PdfDialogSheetSelector: "工作表选择器",
    PdfDialogSheetsFromDashboard: "此仪表板中的特定工作表",
    PdfDialogSheetsFromWorkbook: "此工作簿中的特定工作表",
    PdfDialogThumbnailPageSizeLabel: "页面大小",
    PdfExportFitOneHigh: "至多 1 页高",
    PdfExportFitOneWide: "至多 1 页宽",
    PdfExportFitTwoHigh: "至多 2 页高",
    PdfExportFitTwoWide: "至多 2 页宽",
    PdfExportGeneratingPdf: "正在生成 PDF...",
    PdfExportMessageError: "生成 PDF 时出错!",
    PdfExportMessageSettings: "正从服务器获取 PDF 设置。",
    PdfExportMessageSettingsError: "错误:未能从服务器中检索 PDF 设置。",
    PdfExportPageOrientationLandscape: "横向",
    PdfExportPageOrientationPortrait: "纵向",
    PdfExportPageOrientationPrinter: "打印机",
    PdfExportPageScaleAuto: "自动",
    PdfExportPageScalePercent: "{0}%",
    PdfExportPageSizeA3: "A3",
    PdfExportPageSizeA4: "A4",
    PdfExportPageSizeA5: "A5",
    PdfExportPageSizeB4: "B4",
    PdfExportPageSizeB5: "B5",
    PdfExportPageSizeExecutive: "行政公文纸",
    PdfExportPageSizeFolio: "对开纸",
    PdfExportPageSizeLedger: "帐簿",
    PdfExportPageSizeLegal: "法律",
    PdfExportPageSizeLetter: "信纸",
    PdfExportPageSizeNote: "便笺",
    PdfExportPageSizeQuarto: "四开",
    PdfExportPageSizeStatement: "报表",
    PdfExportPageSizeTabloid: "新闻稿",
    PdfExportPageSizeUnspecified: "未指定",
    PdfExportTitlePDF: "下载 PDF",
    PressBackButtonMessage: "使用后退按钮返回到有效视图。",
    PrintPdfDialogContentRequired: "至少选择一个要下载的工作表。",
    PrintPdfDialogMessage: "已生成 PDF 文件。",
    PrintPdfDialogTitle: "下载 PDF",
    QuantitativeColorCenter: "居中",
    QuantitativeColorDialogTitle: "编辑颜色 {0}",
    QuantitativeColorEnableSteps: "渐变颜色",
    QuantitativeColorEnd: "结束",
    QuantitativeColorEndSwatch: "结束颜色，自定义颜色 {0}",
    QuantitativeColorFullColorRange: "使用完整颜色范围",
    QuantitativeColorHideAdvanced: "隐藏高级",
    QuantitativeColorIncludeTotals: "包括合计",
    QuantitativeColorPaletteLabel: "调色板",
    QuantitativeColorReset: "重置",
    QuantitativeColorReverse: "反向",
    QuantitativeColorShowAdvanced: "显示高级",
    QuantitativeColorStart: "开始",
    QuantitativeColorStartSwatch: "开始颜色，自定义颜色 {0}",
    QuantitativeColorSteps: "步骤",
    QuickFilterAll: "(全部)",
    QuickFilterAllValues: "所有值",
    QuickFilterApply: "应用",
    QuickFilterCancel: "取消",
    QuickFilterClearDisabled: "显示所有值",
    QuickFilterClearEnabled: "单击以显示所有值",
    QuickFilterConditionalsCondition: "条件",
    QuickFilterConditionalsLimit: "限制",
    QuickFilterDomainCascading: "分层结构中的所有值",
    QuickFilterDomainCascadingContext: "分层结构和上下文中的所有值",
    QuickFilterDomainContext: "上下文中的所有值",
    QuickFilterDomainDatabase: "数据库中的所有值",
    QuickFilterDomainRelevant: "仅相关值",
    QuickFilterDomainShowFewerValues: "显示更少值",
    QuickFilterDomainShowMoreValues: "显示更多值",
    QuickFilterExclusive: "排他",
    QuickFilterInclusive: "包含",
    QuickFilterMultiSelect: "多个",
    QuickFilterMultipleValues: "(多个值)",
    QuickFilterNoItems: "无项目。",
    QuickFilterNonNullValues: "非 Null 值",
    QuickFilterNone: "(无)",
    QuickFilterOnlyNullValues: "仅 Null 值",
    QuickFilterSearch: "搜索",
    QuickFilterSearchAddItemCtrlEnter: "添加项目(Ctrl+Enter)",
    QuickFilterSearchAddItemEnter: "添加项目(Enter)",
    QuickFilterSearchCancel: "取消搜索",
    QuickFilterSearchClearTooltip: "清除(Esc)",
    QuickFilterSearchCloseTooltip: "关闭(Esc)",
    QuickFilterSearchDataIsCaseSensitive: "数据区分大小写。",
    QuickFilterSearchFoundMatches: "找到 {0} 个匹配项",
    QuickFilterSearchHint: "输入要搜索的文本",
    QuickFilterSearchInvalidDataMemberSingular: "“{0}”不是筛选器的有效成员。",
    QuickFilterSearchInvalidDataMembersDialogTitle: "数据成员无效",
    QuickFilterSearchInvalidDataMembersPlural: "以下值不是筛选器的有效成员:",
    QuickFilterSearchNoMatches: "无匹配项。",
    QuickFilterSearchTooltip: "搜索(Enter)",
    QuickFilterShowContextMenu: "显示快速筛选器上下文菜单",
    QuickFilterShowLargerRange: "显示更大的范围",
    QuickFilterShowSmallerRange: "显示更小的范围",
    QuickFilterSingleSelect: "单个",
    QuickFilterTitleBarExclusive: "{0} (排他)",
    QuickFilterUnknown: "<未知>",
    QuickFilterValuesInRange: "范围中的值",
    QuickFilterValuesInRangeOrNull: "范围中的值或空",
    RedirectToApp: "是否重定向到应用软件商店?",
    RefLineEditorInputTitle: "值:",
    RefreshDataSourceListLabel: "刷新列表",
    RelDateAnchored_curr_day: "锚点日期",
    RelDateAnchored_curr_hour: "锚点小时",
    RelDateAnchored_curr_minute: "锚点分钟",
    RelDateAnchored_curr_month: "锚点月份",
    RelDateAnchored_curr_quarter: "锚点季度",
    RelDateAnchored_curr_second: "锚点秒",
    RelDateAnchored_curr_week: "锚点周",
    RelDateAnchored_curr_year: "锚点年",
    RelDateAnchored_last_day: "昨天",
    RelDateAnchored_last_hour: "前一小时",
    RelDateAnchored_last_minute: "前一分钟",
    RelDateAnchored_last_month: "前一个月",
    RelDateAnchored_last_quarter: "前一个季度",
    RelDateAnchored_last_second: "前一秒",
    RelDateAnchored_last_week: "前一周",
    RelDateAnchored_last_year: "前一年",
    RelDateAnchored_lastn_day: "前 % 天",
    RelDateAnchored_lastn_hour: "前 % 小时",
    RelDateAnchored_lastn_minute: "前 % 分钟",
    RelDateAnchored_lastn_month: "前 % 个月",
    RelDateAnchored_lastn_quarter: "前 % 个季度",
    RelDateAnchored_lastn_second: "前 % 秒",
    RelDateAnchored_lastn_week: "前 % 周",
    RelDateAnchored_lastn_year: "前 % 年",
    RelDateAnchored_next_day: "明天",
    RelDateAnchored_next_hour: "后一小时",
    RelDateAnchored_next_minute: "后一分钟",
    RelDateAnchored_next_month: "后一个月",
    RelDateAnchored_next_quarter: "后一个季度",
    RelDateAnchored_next_second: "后一秒",
    RelDateAnchored_next_week: "后一周",
    RelDateAnchored_next_year: "后一年",
    RelDateAnchored_nextn_day: "后 % 天",
    RelDateAnchored_nextn_hour: "后 % 小时",
    RelDateAnchored_nextn_minute: "后 % 分钟",
    RelDateAnchored_nextn_month: "后 % 个月",
    RelDateAnchored_nextn_quarter: "后 % 个季度",
    RelDateAnchored_nextn_second: "后 % 秒",
    RelDateAnchored_nextn_week: "后 % 周",
    RelDateAnchored_nextn_year: "后 % 年",
    RelDateAnchored_todate_day: "要锚定的日期",
    RelDateAnchored_todate_hour: "要锚定的小时",
    RelDateAnchored_todate_minute: "要锚定的分钟",
    RelDateAnchored_todate_month: "要锚定的月份",
    RelDateAnchored_todate_quarter: "要锚定的季度",
    RelDateAnchored_todate_second: "要锚定的秒",
    RelDateAnchored_todate_week: "要锚定的周",
    RelDateAnchored_todate_year: "要锚定的年",
    RelDateFilterDays: "天",
    RelDateFilterHours: "小时",
    RelDateFilterMinutes: "分钟",
    RelDateFilterMonths: "月",
    RelDateFilterPreview: "{0} 到 {1}",
    RelDateFilterQuarters: "季度",
    RelDateFilterWeeks: "周",
    RelDateFilterYears: "年",
    RelDatePickerFiveYears: "5 年",
    RelDatePickerFiveYearsAbbrev: "5 年",
    RelDatePickerOneDay: "1 天",
    RelDatePickerOneDayAbbrev: "1 天",
    RelDatePickerOneMonth: "1 个月",
    RelDatePickerOneMonthAbbrev: "1 个月",
    RelDatePickerOneWeek: "1 周",
    RelDatePickerOneWeekAbbrev: "1 周",
    RelDatePickerOneYear: "1 年",
    RelDatePickerOneYearAbbrev: "1 年",
    RelDatePickerThreeMonths: "3 个月",
    RelDatePickerThreeMonthsAbbrev: "3 个月",
    RelDate_curr_day: "今天",
    RelDate_curr_hour: "本小时",
    RelDate_curr_minute: "本分钟",
    RelDate_curr_month: "本月",
    RelDate_curr_quarter: "本季度",
    RelDate_curr_second: "本秒",
    RelDate_curr_week: "本周",
    RelDate_curr_year: "本年",
    RelDate_last_day: "昨天",
    RelDate_last_hour: "前一小时",
    RelDate_last_minute: "前一分钟",
    RelDate_last_month: "前一个月",
    RelDate_last_quarter: "前一个季度",
    RelDate_last_second: "前一秒",
    RelDate_last_week: "前一周",
    RelDate_last_year: "前一年",
    RelDate_lastn_day: "前 % 天",
    RelDate_lastn_hour: "前 % 小时",
    RelDate_lastn_minute: "前 % 分钟",
    RelDate_lastn_month: "前 % 个月",
    RelDate_lastn_quarter: "前 % 个季度",
    RelDate_lastn_second: "前 % 秒",
    RelDate_lastn_week: "前 % 周",
    RelDate_lastn_year: "前 % 年",
    RelDate_next_day: "明天",
    RelDate_next_hour: "后一小时",
    RelDate_next_minute: "后一分钟",
    RelDate_next_month: "后一个月",
    RelDate_next_quarter: "后一个季度",
    RelDate_next_second: "后一秒",
    RelDate_next_week: "后一周",
    RelDate_next_year: "后一年",
    RelDate_nextn_day: "后 % 天",
    RelDate_nextn_hour: "后 % 小时",
    RelDate_nextn_minute: "后 % 分钟",
    RelDate_nextn_month: "后 % 个月",
    RelDate_nextn_quarter: "后 % 个季度",
    RelDate_nextn_second: "后 % 秒",
    RelDate_nextn_week: "后 % 周",
    RelDate_nextn_year: "后 % 年",
    RelDate_todate_day: "本日迄今",
    RelDate_todate_hour: "本小时迄今",
    RelDate_todate_minute: "本分钟迄今",
    RelDate_todate_month: "本月迄今",
    RelDate_todate_quarter: "本季度迄今",
    RelDate_todate_second: "本秒迄今",
    RelDate_todate_week: "本周迄今",
    RelDate_todate_year: "本年迄今",
    RequestAbortedByBrowser: "浏览器已中止请求",
    RequestCountExceededTitle: "已超出请求计数",
    RequestCountExceededWarning: "请求计数在分配的时间内已超出允许数量。",
    RowByColumn: "{0} 行 x  {1} 列",
    RowByColumns: "{0} 行 x {1} 列",
    RowCountLabel: "行",
    RowsByColumn: "{0} 行 x {1} 列",
    RowsByColumns: "{0} 行 x {1} 列",
    Saturday: "星期六",
    SaturdayShort: "周六",
    SaveAsFailedMessage: "您没有保存此工作簿的权限。请联系管理员以获得帮助。",
    SaveIncompleteWorkbookWarning: "发布此工作簿时，并非所有视图都是共享的。保存此工作簿将覆盖原始工作簿，并且会丢失未共享的视图。请考虑改用“另存为”。",
    SaveNoPublishedSheetsBody: "工作簿至少必须有一个发布的工作表才能保存。请右键单击标签以发布工作表。",
    SaveNoPublishedSheetsTitle: "无法保存",
    ScheduleDailyDescription: "每天于 {0}",
    ScheduleEvery30MinutesDescription: "每 30 分钟一次，在小时之后的第 15 分钟和第 45 分钟",
    ScheduleEveryOneHourAtXMinutesPastDescription: "每小时一次，在小时之后的第 {0} 分钟",
    ScheduleEveryOneHourDescription: "每小时",
    ScheduleEveryXHoursStartingAtYDescription: "每 {0} 个小时一次，始于 {1}",
    ScheduleEveryXMinutesDescription: "每 {0} 分钟一次",
    ScheduleHourlyDescription: "每隔 {0} 从 {1} 到 {2}",
    ScheduleMonthlyDescription: "在每月第 {0} 天的 {1}",
    ScheduleMonthlyDescriptionLast: "在每月最后一天的 {0}",
    ScheduleMonthlyDescriptionSecondToLast: "在每月倒数第二天的 {0}",
    ScheduleWeeklyDescription: "每周 {1} 的 {0}",
    SearchDataSources: "搜索数据源",
    SearchResultsNotShownPlural: "未显示 {0} 个结果",
    SearchResultsNotShownSingular: "未显示 1 个结果",
    SearchResultsNotShownZero: "未显示 0 个结果",
    SecondEnding: "第 {0}",
    SecurityBlockedURLActionHeader: "URL 被阻止",
    SecurityBlockedURLActionMessage: "已阻止一个可能不安全的 URL。",
    SelectDataSource: "选择数据源",
    SelectDataSourcePublishedDSDoesNotExist: "所选数据源在服务器上不存在。",
    SelectDataSourcePublishedDSSubError: "选择其他数据源",
    SelectLinkLabel: "选择",
    SelectText: "选择",
    SelectedMarksText: "{1} 的 {0} 个标记",
    September: "九月",
    SeptemberShort: "九月",
    SerialScheduleDescription: "{0} - {1}",
    SerialScheduleDescriptionSuffix: "连续(较慢)",
    ServerAdmin: "服务器管理员",
    ServerDataSourceConnectedWorkbooks: "工作簿",
    ServerDataSourceConnectedWorkbooksTooltip: "连接到数据源的工作簿数",
    ServerDataSourceConnectionType: "连接类型",
    ServerDataSourceConnectsTo: "连接到",
    ServerDataSourceConnectsToSeveral: "{0} + {1}",
    ServerDataSourceExtract: "数据提取",
    ServerDataSourceLive: "实时",
    ServerDataSourceLiveOrLastExtract: "实时/上次数据提取时间",
    ServerDataSourceName: "名称",
    ServerDataSourceOwner: "所有者",
    ServerDataSourceProject: "项目",
    ServerDataSourceTotalViews: "视图: 全部",
    ServerErrorGeneral: "与服务器通信时出错({0})。<br>这可能是临时出现的网络问题。请重试该操作。<br>如果这种情况仍然存在，请与系统管理员联系。",
    ServerErrorInvalidJSON: "与服务器通信时出错(JSON 无效)。",
    ServerErrorRejected: "服务器已拒绝请求",
    ServerErrorRejectedMessage: "由于请求错误，服务器无法进行响应。<br>这可能是临时出现的网络问题。请重试该操作。<br>如果这种情况仍然存在，请与系统管理员联系。",
    ServerErrorTitle: "服务器错误",
    ServerErrorUnexpected: "意外服务器错误",
    SessionEndedAlertMessage: "是否要重置视图?",
    SessionEndedAlertTitle: "服务器已结束会话",
    SessionForbiddenActionMsg: "您未被授权执行此操作。",
    SessionForbiddenActionTitle: "禁止的操作",
    SessionRecoveryWarning: "会话中断。您的工作簿已还原为之前的状态。",
    SessionUnknownErrorTitle: "未知服务器错误",
    ShareDialogAndroidLinkText: "轻触图标以打开链接",
    ShareDialogDisplayOptions: "显示选项",
    ShareDialogDoneButton: "完成",
    ShareDialogEmail: "电子邮件:",
    ShareDialogEmailHelp: "将链接复制并粘贴到电子邮件中",
    ShareDialogEmailLink: "电子邮件",
    ShareDialogEmbed: "嵌入:",
    ShareDialogEmbedCodeTableauText: "了解有关 Tableau 的信息",
    ShareDialogEmbedHelp: "复制并粘贴 HTML 代码以在您的网站中嵌入视图",
    ShareDialogEnterUriForBlogEntry: "输入博客条目的 URI",
    ShareDialogEnterValueBetween: "输入介于 {0} 和 {1} 之间的值",
    ShareDialogFacebookLink: "Facebook",
    ShareDialogHeight: "高度:",
    ShareDialogInvalidHeight: "高度无效。",
    ShareDialogInvalidWidth: "宽度无效。",
    ShareDialogLink: "链接:",
    ShareDialogMobileEmailText: "轻触图标以通过电子邮件发送链接",
    ShareDialogMobileLinkText: "轻触并按住图标以访问其他共享选项",
    ShareDialogPleaseEnterIntegerBetween: "请输入介于 {0} 和 {1} 之间的整数",
    ShareDialogShowTabs: "显示选项卡",
    ShareDialogShowToolbar: "显示工具栏",
    ShareDialogTitle: "共享视图",
    ShareDialogTitleForView: "共享视图",
    ShareDialogTwitterLink: "推文",
    ShareDialogUrlForRssLinks: "RSS 链接的 URL:",
    ShareDialogWaitingEmbedMessage: "正在创建自定义嵌入代码...",
    ShareDialogWaitingLinkMessage: "正在创建自定义链接...",
    ShareDialogWidth: "宽度:",
    ShareViewOptions: "共享视图选项",
    SheetReconnectEditConnectionLabel: "编辑连接",
    SheetReconnectEditingNotSupported: "此数据连接当前不支持编辑。",
    SheetReconnectErrorMessage: "{0}。",
    SheetReconnectLocateFileLabel: "查找文件",
    SheetReconnectSignInLabel: "登录",
    SheetReconnectSubtitle: "连接到“{0}”数据源时出现问题。",
    SheetReconnectTitle: "工作表不可用",
    ShowAliases: "显示别名",
    ShowDetailsLabel: "显示详细信息",
    ShowHiddenFields: "显示隐藏字段",
    SignOutFailedMessage: "未能注销。请重试。",
    SiteAdmin: "站点管理员",
    SizeLegendTextMarkSwatch: "Abc",
    SmoothTooltipsOnboardingText: "用双指滚动",
    SnapshotApplicationErrorMessage: "无法将 {0} 中的快照应用于此视图",
    SortAtoZAscending: "A 至 Z 升序",
    SortAtoZAscendingPerTable: "按表 A 至 Z 升序",
    SortDataSourceOrder: "数据源顺序",
    SortFields: "排序字段",
    SortModified: "修改时间",
    SortZtoADescending: "Z 至 A 降序",
    SortZtoADescendingPerTable: "按表 Z 至 A 降序",
    SpecialAll: "全部",
    SpecialError: "#错误",
    SpecialManyValues: "*",
    SpecialMissing: "#缺少",
    SpecialNoAccess: "#NoAccess",
    SpecialRagged: "#不规则",
    SpecialSkipped: "#跳过",
    SpecialValuesHeading: "特殊值(例如: NULL)",
    SpecialValuesMarkLabel: "标记",
    SpecialValuesMarksHideBreakLines: "隐藏(断开线)",
    SpecialValuesMarksHideConnectLines: "隐藏(连接线)",
    SpecialValuesMarksShowAtDefaultValue: "在默认值处显示",
    SpecialValuesMarksShowAtIndicator: "在指示器上显示",
    SpecialValuesTextLabel: "文本",
    SpecialValuesTextPlaceholder: "(空白)",
    SpecialWildcard: "通配符",
    StopUsingAsLinkingField: "停止使用 {0} 作为链接字段",
    StoryContentPaneBlankButton: "空白",
    StoryContentPaneDuplicateButton: "复制",
    StoryContentPaneSaveAsNewPointButton: "另存为新的",
    StoryContentPaneTitle: "故事",
    StoryContentShowCaptions: "显示标题",
    StoryContentShowTitles: "显示标题",
    StoryEmptyCaptionText: "添加标题",
    StoryEmptyDashboardStoryPointSubtitle: "将工作表添加到仪表板中。",
    StoryEmptyDashboardStoryPointTitle: "此仪表板为空。",
    StoryEmptyFlipboardSubtitle: "在此添加工作表",
    StoryEmptyFlipboardTitle: "从左侧的列表中双击",
    StoryEmptyWorksheetStoryPointSubtitle: "在工作表中创建可视化项。",
    StoryEmptyWorksheetStoryPointTitle: "此工作表为空。",
    StoryNavigatorStyle: "导航器样式",
    StoryNavigatorTypeArrowOnly: "仅限箭头",
    StoryNavigatorTypeCaption: "标题框",
    StoryNavigatorTypeDot: "点",
    StoryNavigatorTypeNumber: "数字",
    StoryNavigatorUpdated: "已更新",
    StoryNewPointSectionTitle: "新建故事点",
    StoryPointDeleteTooltip: "删除",
    StoryPointNavigatorLocationBottom: "底部",
    StoryPointNavigatorLocationTitle: "导航器位置",
    StoryPointNavigatorLocationTop: "顶部",
    StoryPointNavigatorShowArrows: "显示箭头",
    StoryPointRevertTooltip: "恢复",
    StoryPointSaveAsNewTooltip: "另存为新点",
    StoryPointUpdateButton: "更新",
    SubscribeButtonTooltip: "订阅",
    SubscribeCancel: "取消",
    SubscribeContent: "内容:",
    SubscribeDone: "完成",
    SubscribeEnterAddress: "要接收订阅，请输入您的电子邮件地址。",
    SubscribeFailure: "订阅失败。",
    SubscribeInvalidAddress: "请输入有效的电子邮件地址。 ",
    SubscribeNext: "下一步",
    SubscribeOthers: "订阅其他",
    SubscribeOthersFailed: "无法完成 {0} 位订阅者的订阅。",
    SubscribeOthersSearchPlaceholder: "订阅者姓名或用户名",
    SubscribeOthersSuccess: "已创建 {0} 个订阅。",
    SubscribeSelf: "为我订阅",
    SubscribeSelfLabel: "我要订阅",
    SubscribeSheet: "此工作表",
    SubscribeSubject: "主题:",
    SubscribeSubscribe: "订阅",
    SubscribeSuccess: "订阅已成功保存。",
    SubscribeTitle: "订阅",
    SubscribeTo: "收件人:",
    SubscribeViewsToggleLabel: "订阅",
    SubscribeWorkbook: "工作簿中的工作表",
    SuggestBinSizeButtonText: "建议",
    SumOf: "以下项的总和:",
    Sunday: "星期天",
    SundayShort: "周日",
    SwapSheets: "交换工作表",
    TabAuthCategoricalColorEditorAssignPalette: "分配调色板",
    TabAuthCategoricalColorEditorReset: "重置",
    TabAuthCategoricalColorEditorSelectItem: "选择数据项",
    TabAuthCategoricalColorEditorSelectPalette: "选择调色板",
    TabAuthColorEditButton: "编辑颜色...",
    TabAuthColorEditLabel: "颜色",
    TabAuthColorEditLegendButtonTooltip: "编辑颜色...",
    TabAuthColorEditorDialogTitle: "编辑颜色 [{0}]",
    TabAuthMarksColorBorderLabel: "边界",
    TabAuthMarksColorHaloLabel: "光环",
    TabAuthSaveDatasourceConfirmMsg: "保存数据源“{0}”以在服务器上共享使用?",
    TabAuthSaveDatasourceDialogTitle: "确认保存数据源",
    TabAuthSaveDatasourceErrorDialogTitle: "保存数据源错误",
    TabAuthSaveDatasourceNotReplacedSuccessMessage: "数据源“{0}”已保存，但在替换此工作簿的连接时出现问题。",
    TabAuthSaveDatasourceNotReplacedSuccessTitle: "保存和替换数据源",
    TabAuthSaveDatasourceReplaceCheckboxLabel: "更新工作簿以连接到保存的数据源",
    TabAuthSaveDatasourceReplacedSuccessMessage: "已保存您的数据源。",
    TabAuthSaveDatasourceReplacedSuccessTitle: "保存和替换数据源",
    TabAuthSaveDatasourceSuccessDialogTitle: "保存数据源成功",
    TabAuthSaveDatasourceSuccessMessage: "您的数据源已保存。项目设置确定此数据源的“连接到”和其他权限。浏览到“数据源”页面以查看此数据源及其属性。",
    TableCalcAddSecondary: "添加辅助计算",
    TableCalcAtTheLevel: "所在级别",
    TableCalcComputeCompoundedRate: "计算复利率",
    TableCalcComputeTotalAcrossPages: "跨所有页面计算合计",
    TableCalcComputeUsing: "计算依据",
    TableCalcDialogTitle: "表计算",
    TableCalcInvalidRestartEveryField: "<无效>",
    TableCalcMissingSortField: "<缺失>",
    TableCalcNestedCalculations: "嵌套计算",
    TableCalcPrimaryTitle: "主要计算类型",
    TableCalcRelativeTo: "相对于",
    TableCalcRestartingEvery: "重新启动间隔",
    TableCalcSecondaryTitle: "从属计算类型",
    TableCalcShowCalculationAssistance: "显示计算帮助",
    TableCalcSingleTitle: "计算类型",
    TableCalcSortAscending: "升序",
    TableCalcSortAutomatic: "特定维度",
    TableCalcSortCustom: "自定义",
    TableCalcSortDescending: "降序",
    TableCalcSortOrder: "排序顺序",
    TableCalcSpecificDimensions: "特定维度",
    TableCalcVisualStructure: "可视化结构",
    TableCalcWindowCurrentValue: "当前值",
    TableCalcWindowNullSetting: "若无足够的值则为空",
    TableauMobileWebBannerLabel: "Tableau",
    ThirdEnding: "第 {0}",
    Thursday: "星期四",
    ThursdayShort: "周四",
    TimeLimitExceededTitle: "超出会话时间限制",
    TimeLimitExceededWarning: "当前可视化计算已超出会话时间限制。",
    ToolbarAboutTableau: "关于 Tableau",
    ToolbarConnectToDataSource: "添加新的数据源",
    ToolbarCurrentView: "当前视图",
    ToolbarCustomViewsDefault: "{0} (默认)",
    ToolbarCustomViewsDeleteButtonTooltip: "删除此视图",
    ToolbarCustomViewsEmptyPlaceholder: "尚未保存任何内容",
    ToolbarCustomViewsEnterManageButtonText: "管理",
    ToolbarCustomViewsErrorChangingPublicPrivateState: "更新自定义视图上的公共/私有状态时出错。",
    ToolbarCustomViewsErrorDeleting: "删除自定义视图时出错。",
    ToolbarCustomViewsErrorInvalidName: "请输入有效的自定义视图名称。",
    ToolbarCustomViewsErrorRenaming: "重命名自定义视图时出错。",
    ToolbarCustomViewsErrorSavingView: "保存自定义视图时出错。",
    ToolbarCustomViewsErrorSettingDefault: "设置默认自定义视图时出错。",
    ToolbarCustomViewsExitManageButtonText: "完成",
    ToolbarCustomViewsHideViewButtonTooltipWhenPrivate: "此视图是私有视图",
    ToolbarCustomViewsHideViewButtonTooltipWhenPublic: "此视图是公共视图",
    ToolbarCustomViewsMakeItMyDefault: "将其设为我的默认值",
    ToolbarCustomViewsMyViews: "我的视图",
    ToolbarCustomViewsOriginalView: "原始",
    ToolbarCustomViewsOtherViews: "其他视图",
    ToolbarCustomViewsRenameButtonTooltip: "重命名此视图",
    ToolbarCustomViewsRenameUIClearButtonTooltip: "取消",
    ToolbarCustomViewsRenameUIPlaceholderText: "重命名此视图",
    ToolbarCustomViewsSave: "保存",
    ToolbarCustomViewsSaveAreaFillerTextManage: "管理",
    ToolbarCustomViewsSaveAreaFillerTextSelect: "选择自定义视图",
    ToolbarCustomViewsSaveButtonDisabledTitle: "请在文本字段中输入自定义视图的名称。",
    ToolbarCustomViewsSetDefaultButtonTooltip: "将此视图设为您的默认视图",
    ToolbarCustomViewsSetDefaultButtonTooltipWhenCurrent: "这是您的当前默认视图",
    ToolbarCustomViewsShareItWithOthers: "将其公开",
    ToolbarCustomViewsTemplate: "视图: {0}",
    ToolbarCustomViewsViewNamePlaceholder: "为此视图命名",
    ToolbarDisabledCrosstabDownloadExplanation: "无法下载交叉表。",
    ToolbarDisabledDataDownloadExplanation: "无法下载数据。",
    ToolbarDisabledDownloadExplanation: "单击视图以启用数据和交叉表下载",
    ToolbarDisabledPdfImageDownloadExplanation: "需要下载图像或 PDF 的权限。",
    ToolbarDisabledPdfPptImageDownloadExplanation: "需要图像/PDF 下载权限。",
    ToolbarDisabledWorkbookDownloadExplanation: "需要权限才能下载工作簿。",
    ToolbarDownload: "下载",
    ToolbarDownloadSelectFormat: "选择您的文件格式。",
    ToolbarEdit: "编辑",
    ToolbarEmbedTitle: "嵌入代码",
    ToolbarEnterFullscreen: "全屏",
    ToolbarExitFullscreen: "退出全屏",
    ToolbarExport: "下载",
    ToolbarExportCrosstab: "交叉表",
    ToolbarExportData: "数据",
    ToolbarExportImage: "图像",
    ToolbarExportPowerPoint: "PowerPoint",
    ToolbarLearnMoreAboutTableau: "了解有关 Tableau 的更多信息",
    ToolbarLearnMoreAboutTableauPublic: "了解有关 Tableau Public 的更多信息",
    ToolbarMoreByAuthor: "此作者提供的更多内容",
    ToolbarMoreInfo: "更多信息",
    ToolbarOriginalView: "原始视图",
    ToolbarPauseAutomaticUpdates: "暂停自动更新",
    ToolbarPrintToPdf: "PDF",
    ToolbarPublicAvailablePlatforms: "可用于 {0} 和 {1}",
    ToolbarPublicDownloadLabelMobile: "了解更多信息",
    ToolbarPublicDownloadLabelWeb: "获取应用软件",
    ToolbarPublicExplanationText: "创建交互式的图表、地图、仪表板和应用软件。将它们发布到 Web 上的任何地方。任何人都能这样做。而且还免费。",
    ToolbarPublicExplanationTitle: "什么是 Tableau Public?",
    ToolbarRefreshData: "刷新此视图的数据",
    ToolbarResumeAutomaticUpdates: "继续自动更新",
    ToolbarRevertAll: "全部恢复",
    ToolbarSendTitle: "链接",
    ToolbarSetCurrentPage: "设置当前页面",
    ToolbarShare: "共享",
    ToolbarShowPerformanceRecording: "性能",
    ToolbarSubscribeAddGroupsHeader: "在群组中添加用户",
    ToolbarSubscribeAddGroupsLabel: "为群组中的用户订阅",
    ToolbarSubscribeAddGroupsPlaceholder: "在群组中添加用户",
    ToolbarSubscribeAddUsersHeader: "添加用户",
    ToolbarSubscribeAddUsersLabel: "为用户订阅",
    ToolbarSubscribeAddUsersPlaceholder: "添加用户",
    ToolbarSubscribeAllView: "整个工作簿",
    ToolbarSubscribeDataPresentCheckbox: "视图为空的情况下不发送",
    ToolbarSubscribeEmailPlaceholder: "电子邮件",
    ToolbarSubscribeFormat: "格式",
    ToolbarSubscribeInclude: "包括",
    ToolbarSubscribeMessageEditorPlaceholder: "添加自定义消息",
    ToolbarSubscribeMessageLabel: "消息",
    ToolbarSubscribeMessagePlaceholder: "添加自定义消息（可选）",
    ToolbarSubscribeSchedule: "计划",
    ToolbarSubscribeSubjectPlaceholder: "主题",
    ToolbarSubscribeSubmitButton: "订阅",
    ToolbarSubscribeSubmitDisabledTitle: "请确保您有有效的计划、电子邮件地址和主题以便进行订阅。",
    ToolbarSubscribeThisView: "此视图",
    ToolbarSubscribeToImage: "图像",
    ToolbarSubscribeToImageAndPdf: "图像和 PDF",
    ToolbarSubscribeToPdf: "PDF",
    ToolbarToggleAutoUpdate: "切换自动更新",
    ToolbarViewCount: "{0} 个视图",
    ToolbarWorkbook: "Tableau 工作簿",
    TooltipPanZoomMessage: "双击可缩放/按住可平移",
    TrendLineDialogFactorsSectionLabel: "包括以下字段作为因素:",
    TrendLineDialogModelTypeSectionLabel: "模型类型",
    TrendLineDialogOptionsSectionLabel: "选项",
    Tuesday: "星期二",
    TuesdayShort: "周二",
    UbertipClearSelection: "清除<br/>选择",
    UbertipCommand1Mobile: "清除<br/>选择",
    UbertipCommand7Mobile: "查看数据",
    UbertipItemsSelected: "项已选择",
    UbertipTooltip_Action_DownMobile: "下钻查询",
    UbertipTooltip_Action_UpMobile: "上钻查询",
    UbertipTooltip_ExcludeMobile: "排除",
    UbertipTooltip_GroupMobile: "组成员",
    UbertipTooltip_KeepOnlyMobile: "只保留",
    UbertipTooltip_SortAscendingMobile: "升序排序",
    UbertipTooltip_SortDescendingMobile: "降序排序",
    UbertipTooltip_SplitMobile: "取消成员分组",
    UbertipTooltip_ViewDataMobile: "查看数据",
    UnhandledExceptionMessage: "发生意外错误。如果仍然收到此错误，请与 Tableau Server 管理员联系。<br>会话 ID: {0}<br>{1}",
    UnhandledExceptionTitle: "意外错误",
    UnusedFilesInSaveWorkbookSavedMessage: "您有一些未包括在数据源中的文本文件。如果要保存这些文件，请将它们添加到数据源。",
    UploadBytes: "字节",
    UploadGB: "GB",
    UploadKB: "KB",
    UploadMB: "MB",
    UseAsLinkingField: "将 {0} 用作链接字段",
    UserHasNoEmailAddressWarning: "用户在 Tableau 中没有电子邮件地址",
    ViewCommentsMobileWebBannerLabel: "若要查看注释，",
    ViewDataDownloadDataAsFile: "将所有行下载为文本文件",
    ViewDataShowAllColumns: "显示所有列",
    ViewDataShowingRows: "显示前 {0} 行。",
    ViewDataSummary: "摘要",
    ViewDataUnderlying: "完整数据",
    VizObjectTypeReferenceLine: "参考线",
    WaitDialogDefaultTitleStatus: "正在处理...",
    WarningTitle: "警告",
    WebZoneHttpsEmbedHttpAuthoring: "由于服务器正在运行 HTTPS，因此必须使用 https:// 而不是使用 http:// 来指定此网页对象的 URL",
    WebZoneHttpsEmbedHttpView: "无法显示网页对象(URL 必须以 https:// 开头)",
    WebZoneUrlDialogTitle: "编辑 URL",
    Wednesday: "星期三",
    WednesdayShort: "周三",
    WindowTableCalcNextValuesLabel: "后面的值",
    WindowTableCalcPreviousValuesLabel: "前面的值",
    WindowTableCalcSummarizeUsing: "根据以下因素汇总值",
    WorkbookTemplatesCategoryLabel: "仪表板起始模板",
    WorkbookTemplatesExtractErrorBannerActionMessage: "继续使用示例数据",
    WorkbookTemplatesExtractErrorBannerMessage: "无法在仪表板中加载您的数据。有关详细信息，请检查您的电子邮件。",
    WorkbookTemplatesPublishErrorBannerActionMessage: "重试",
    WorkbookTemplatesPublishErrorBannerMessage: "无法发布工作簿。如果问题仍然存在，请重试或联系您的管理员。",
    WorkbookTemplatesSampleData: "正在生成数据提取...",
    WorkbookTemplatesServiceDownMessage: "仪表板起始模板目前不可用。请稍后重试。",
    WorkbookTemplatesSuccessBannerActionMessage: "重新加载工作簿",
    WorkbookTemplatesSuccessBannerMessage: "您的数据提取已完成。请重新加载工作簿以开始浏览。",
    WorkbookTemplatesTypeLabel: "起始模板"
  };

  function replaceAll(s, oldValue, newValue) {
    newValue = (newValue === undefined || newValue === null) ? '' : newValue;
    return s.split(oldValue).join(newValue);
  }

  w.tab = w.tab || {};
  if (!tab.Strings) {
    tab.Strings = {
      noLoc: function(str) { return str; },
      getString: function(strKey) { return typeof (tab.Strings[strKey]) === 'undefined' ? '!' + strKey + '!': tab.Strings[strKey]; }
    };
    for (var key in s) {
      if (s.hasOwnProperty(key)) {
        tab.Strings[key] = function() {
          var k = key, hasParams = /{[^}{]+}/.test(s[k]);
          return hasParams ?
            function() {
              var formattedString = s[k];
              for (var i = 0, len = arguments.length; i < len; i++) {
                formattedString = replaceAll(formattedString, '{' + i + '}', arguments[i]);
              }
              return formattedString;
            } :
            s[k];
        }();
      }
    }
  }
}(window));
